2017-01-12 14:55:36 [ERROR] {jdbc.OperateDB.getMetaInf(OperateDB.java:54)} - Exception occurs when getMetaInf data
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395)
	at com.mysql.jdbc.ResultSetMetaData.getColumnName(ResultSetMetaData.java:243)
	at jdbc.OperateDB.getMetaInf(OperateDB.java:48)
	at runTest.TestConfig.main(TestConfig.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2017-01-12 14:55:36 [ERROR] {runTest.TestConfig.main(TestConfig.java:28)} - exception occurs in main()
java.lang.NullPointerException
	at runTest.TestConfig.main(TestConfig.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
